(define (max a b) (if (> a b) a b))
(define (min a b) (if (> a b) b a))
(define (gcd a b)
    (if (= (modulo (max a b) (min a b)) 0)
    (min a b)
    (if (= (max a b) a)
  (gcd b (modulo a b))
  (gcd a (modulo b a))
  )
  )
)