(define (swap s)
    (define (iter lst lt)
    (cond ((null? lst) (reverse lt))
        ((null? (cdr lst)) (reverse (cons (car lst) lt)))
        (else (iter (cdr (cdr lst)) (cons (car lst) (cons (car (cdr lst)) lt)))
    )
    )
    )
    (iter s '())
    )